// generated by NAnt buildscript
    
#ifndef _LIBVER_H_
#define _LIBVER_H_

  // macro to convert version number to text
  #define LIB_VERSION_ASTEXT2(x)     #x
  #define LIB_VERSION_ASTEXT(x) LIB_VERSION_ASTEXT2(x)

/*****************************************************************************
 * LIB version number
 ****************************************************************************/
   // Major version number
  #define LIB_A_VERSION      4
  #define LIB_A_VERSION_STR  LIB_VERSION_ASTEXT(LIB_A_VERSION)

  // Minor version number
  #define LIB_B_VERSION      0
  #define LIB_B_VERSION_STR  LIB_VERSION_ASTEXT(LIB_B_VERSION)

  // Revision number
  #define LIB_C_VERSION      0
  #define LIB_C_VERSION_STR  LIB_VERSION_ASTEXT(LIB_C_VERSION)
  
  // Build number
  #define LIB_D_VERSION      0
  #define LIB_D_VERSION_STR  LIB_VERSION_ASTEXT(LIB_D_VERSION)
  
  // debug/release
  //
  #ifdef _DEBUG
    #define LIB_VI_BUILDTYPE_STR   "debug"
  #else
    #define LIB_VI_BUILDTYPE_STR   "release"
  #endif

/*****************************************************************************
 * LIB version information
 ****************************************************************************/
  #define LIB_VI_COPYRIGHT_STR     "Copyright 2005-2015 IXXAT Automation GmbH, all rights reserved"  
  #define LIB_VI_COMPANY_NAME_STR  "IXXAT Automation GmbH"
  #define LIB_VI_PRODUCT_NAME_STR  "vci4net"     
  #define LIB_VI_SPECIALBUILD_STR  ""  

  #define LIB_VI_FILE_VERS      LIB_A_VERSION, LIB_B_VERSION, LIB_C_VERSION, LIB_D_VERSION
  #define LIB_VI_FILE_VERS_STR  LIB_VERSION_ASTEXT(LIB_VI_FILE_VERS)

#endif
    